container_commands:
    00-migration:
        command: "php /var/app/ondeck/artisan --env=staging make:migration add_paid_to_users_table --table=users"
        command: "php /var/app/ondeck/artisan --env=staging migrate"
